thread 'rustc' panicked at 'assertion failed: !self.substitutions.is_empty()'
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.